### ISSUE TITLE
URL登録時の保存の挙動改善

### ISSUE THREAD

**Issue by contiki9** [rabify-team/rabify#2]
**Service Name:**
[x] rabify CI
[ ] rabify CDN
[ ] rabify PR

**I'm submitting a ...** 

[ ] bug report
[x] feature request

**Current behavior:**
[![Screenshot from Gyazo](https://gyazo.com/d795260a05efcee1d399fc45347576d0/raw)](https://gyazo.com/d795260a05efcee1d399fc45347576d0)

**Expected behavior:**

`/` 有りでも登録されるか `/` なしでないと登録できないとalertがほしいです。

**Steps to reproduce:**
URLの項目を登録。
※キャプチャのものはmac/Chrome

**Comment by rdlabo** [comment]
- / 有りでも登録できるように変更
- URLでない場合にアラートを表示

![スクリーンショット 2020-01-06 17 21 21](https://user-images.githubusercontent.com/9690024/71805312-45fc7280-30a9-11ea-912b-4544a239641a.png)
